BOARD_TAG = uno
ARDUINO_LIBS += SPI Wire LiquidCrystal
#MONITOR_PORT = /dev/ttyUSB0 (will be automatically guessed from IDE prefs)
#USER_LIB_PATH := /home/todd/sketchbook/Brewduino
include /usr/share/arduino/Arduino.mk
